### PR TITLE
ms graph adaptor docs

### PR DESCRIPTION
**Pull request by ritazagoni**

### CODE REVIEW

**Comment by daissatou2** [comment]
@aleksa-krolls I defer to @christad92 as he completed the configuration in Azure. I would be happy to review any Docs on setting up the credential in OpenFn.

**Comment by aleksa-krolls** [comment]
@ritazagoni @christad92 do we have any draft docs on setting up the msgraph oauth credential somewhere? 

if not, then @daissatou2 can you maybe pls draft that in a Google doc for Ayodele to review? We can then later add to the Adaptor overview page.

**Review by aleksa-krolls — CHANGES_REQUESTED** [review]
@christad92 @ritazagoni These docs need work. Major comments: 
1. No link to the main Microsoft Graph API docs: https://learn.microsoft.com/en-us/graph/use-the-api
2. We need a better introduction and context-setting in this doc. You dive _right_ into how to configure Oauth clients, without explaining why (e.g., `To connect with Microsoft Graph API, Oauth is the accepted authentication method. Follow these instructions to set up Oauth access via OpenFn.`)
3. Please address my open comments [in the Documentation gdoc](https://docs.google.com/document/d/1Hs_j3lQNmowbFXriNBB6VrEYU0otC3bhuLwnFjYzdho/edit#heading=h.adqptkcpbou1) - I still have some questions about why some of this info is in here/what is its purpose. For example, the `Scopes` list is really random and there is no explanation on what it's for

**Comment by christad92** [comment]
> @ritazagoni @christad92 do we have any draft docs on setting up the msgraph oauth credential somewhere?
> 
> if not, then @daissatou2 can you maybe pls draft that in a Google doc for Ayodele to review? We can then later add to the Adaptor overview page.

Yes, there is a draft for this on the documentation doc.

**Review by christad92 — COMMENTED** [review]
@ritazagoni great work here. 

But I think there is some work to be done here. 
1. For the MSgraph overview we need to follow the new template as defined here. 
2. For the Authorization/Authentication section, I think we need to create a page for  `Administering Generic OAuth clients and credentials` which will be referenced for adaptors that require OAuth e.g. Salesforce, Google et.c.
3. The last part of this is the **Managing MS Graph Generic OAuth Client on OpenFn** which introduces the topic of creating MS Graph Apps. 

I will take a stab at this next week  -- creating these 3-4 pages and will share for review by Friday. 

cc: @aleksa-krolls

**Comment by christad92** [comment]
@ritazagoni can you close this? I am making a new PR that covers the overview without any extra stuff.

**Comment by aleksa-krolls** [comment]
Abandoned - replaced by another clean PR

**Pull request closed without merging**
