### PR TITLE
Update `CLI` docs

### LINKED ISSUE #339: Add documentation on how to pass state from 1 job to another when working locally vs on platform
The OS4H team expressed confusion on how to pass state from one job to another when working locally during one of thier homework exercises. Please add documentation to docs.openfn.org which explains how to do this and how this is different from working on the platform. Consider creating a new docs page in the Build -> Jobs section, or expanding on this existing [page](https://docs.openfn.org/documentation/jobs/state) which discusses `state`.

### PR DESCRIPTION
**Pull request by mtuchi**
#### Description
Update CLI developer challenge to use workflow execution plan feature, Fixes #339

### CODE REVIEW

**Comment by daissatou2** [comment]
This is a great addition to the CLI page! I know the OS4H team struggled with the concept of running flow jobs locally. Some feedback to consider: 

1. Please specify if job `id` is something that should be made up. Also, should it just be unique to that specific workflow plan file? 
2. Can you name the `id` for the starting job in your example workflow something other than "start"? That confused me a bit. 
3. Can we give an example of a realistic workflow plan? Maybe `getUsers` and then `postUsers`? **With the current docs, I don’t understand how I could format the execution plan so that the output of `getUsers` could automatically be used as the input of `postUsers`.**  Is it not possible to use a file name as the `data`? 
4. What is the difference between “execution plan”, “workflow plan” and workflow execution plan”? I’m seeing all three seemingly referring to the same thing. I think it would be a good idea to use one term. 
5. Can you add the text in italics to the docs? “Execution plan is a powerful feature of @openfn/cli that allows you to define a list of jobs and rules for executing them. You can use an Execution Plan to orchestrate the flow of data between systems, and to handle errors and retries in a structured and automated way. _For example, if you have two jobs in your workflow (GET users from system A & POST users to system B), you can use your execution plan to automatically run both jobs from start to finish. This imitates the [flow and fail trigger patterns](https://docs.openfn.org/documentation/build/triggers#flow-triggers) on the OpenFn platform where a second job should run after the first one succeeds or fails, respectively, using the data returned from the first job._ “
6. After the code snippet on executing the workflow plan (openfn workflow.json -i), include a sentence of what would happen upon execution. For instance “On execution, this workflow plan will first run x job using  x data, then run x job using x data”

**Comment by taylordowns2000** [comment]
@mtuchi , please request a review from me when you've addressed @daissatou2 's changes! excited to get these docs up :-)

**Comment by mtuchi** [comment]
@daissatou2 thank you for the feedback 👌🏽, i have address you comments and fine turned the language a bit,  Also i have added the examples to show how you can run the workflow. Please give it another spin and let me know if it's still confusing or if we can make it better

**Comment by daissatou2** [comment]
@mtuchi I've added some time on your calendar for us to discuss my feedback.

**Review by daissatou2 — CHANGES_REQUESTED** [review]
discussed feedback on a call with Mtuchi.

**Review by taylordowns2000 — APPROVED** [review]
approved from my end. when aicha approves the content we're good to go

**Review by daissatou2 — APPROVED** [review]

**Pull request merged**
