### PR TITLE
Using git

### PR DESCRIPTION
**Pull request by ritazagoni**

### CODE REVIEW

**Comment by aleksa-krolls** [comment]
@ritazagoni Looking good. Confirming you've done the following? 
1. Run the `prettier` linter on these md files to make sure formatting is uniform with rest of docs site? 
2. previewed these changes locally to confirm images, etc. render properly? 

Feedback: 
1. I think your reference img files need to be included in your PR... unless I missed those? 
2. For addtl help at the bottom of this, can we link to another site/website that has documentation on other Git commands? And/or prompt users to post in the Community if they need help?

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
This looks great, @ritazagoni , but how does it relate to [Devtools](https://docs.openfn.org/documentation/devtools/home)? If it should be a separate page, in a separate section, I'd at least want to make sure there's tight alignment with Devtools and plenty of cross-links. In my mind, there isn't much advantage to writing jobs locally unless you're also testing them locally. (This last bit is certainly open to debate! Thoughts? @aleksa-krolls too ?)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 We need this resource.... we have some clients ready to edit locally, but testing locally is too much (they're working up to it). But at least this is helping them have fewer job errors. Next up is more on setting up jobs to test locally. 

If it doesn't go in devtools, where does it go? Maybe somewhere else in `Build`?

**Comment by taylordowns2000** [comment]
Gotcha. Right now @ritazagoni is proposing it go in build. I'm cool with that, just want to make sure there's a nod to devtools (like, at least one link/mention) and confirmation that none of the content of the devtools docs is duplicated here.

**Review by taylordowns2000 — APPROVED** [review]

**Pull request merged**
