### PR TITLE
Various minor docs tweaks and sidebar restructure (aka feedback from Joe)

### PR DESCRIPTION
**Pull request by josephjclark**
* Update the main sidebar structure
* Tweak the About OpenFn page a bit
* Hide a few pages which aren't ready yet
* Upate CLI docs (more examples)
* Fix some bad styling
* Fix some typos

### CODE REVIEW

**Comment by mtuchi** [comment]
@josephjclark i think you should revert the changes in `yarn.lock`, We probably should have a separate PR for that because i have seen it happen on my local machine also in @daissatou machine. 
I am not sure why the `yarn.lock` file gets updated, probably it's related to the version of yarn we are using

**Comment by josephjclark** [comment]
Thank you @mtuchi , I didn't spot that. I did have some trouble getting the server started (on two machines now). I'll get that sorted!

**Review by taylordowns2000 — APPROVED** [review]
@aleksa-krolls , @ritazagoni , this is good for me. please merge if/when you're happy

**Review by aleksa-krolls — APPROVED** [review]

**Comment by aleksa-krolls** [comment]
Thanks @josephjclark  😊

**Pull request merged**
