### PR TITLE
Add devtools tips

### PR DESCRIPTION
**Pull request by ritazagoni**

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
Please include a line about gitignore. By convention, most of these repos ignore a tmp dir, but that's not built in. Users should always ensure they know which files and folders they are ignoring.

**Comment by taylordowns2000** [comment]
@ritazagoni , please change from `gitignore` to `.gitignore` - and verify that you can find that exact file in your own repo!

**Comment by aleksa-krolls** [comment]
@ritazagoni do you have time sometime this week or next to wrap this up? :)

**Comment by taylordowns2000** [comment]
@ritazagoni , @aleksa-krolls , going to implement and merge

**Pull request merged**
