### PR TITLE
Update `CLI` challenges

### PR DESCRIPTION
**Pull request by mtuchi**
#### Implementation checklist
- [x] update job path from `foo/job.js` to `hello.js`
`foo/job.js` does not exist because it's a concept but we have already created `hello.js`. So if someone copied the command without creating `foo/job.js` then it will run without any problem
- [x] Explain what is a job & adaptor or link to the docs before running the first job  "This task teaches how to run a job using `openfn/cli` but we will learn about adaptors in the coming task"
- [x]  ~~Expected output.json~~ to Expected CLI logs
- [x] Remove comments in `state.json` or improve understanding state instruction 
- [x] Image optimization 
- [x] In manipulating data add a summary before the example
- [x] CLI arguments &  Additional arguments 
- [x] In understanding state, add the difference between `console.log(state)` and `console.log(state.data)`
- [x] In manipulating data add links to JS resources for `array.reduce` 
- [x] Add a banner 
     - [x] This CLI challenge will take between 1-2 hrs
     - [x] If you have a question go to community.openfn.org (When you stuck)
     - [x] ~~Link to a specific community thread if available~~

### CODE REVIEW

**Comment by josephjclark** [comment]
I am removing the default state loading (there are now no errors if state is not passed) and updating the test command output in kit.

I suggest we go ahead and update this now to reflect the changes

**Comment by mtuchi** [comment]
> I am removing the default state loading (there are now no errors if state is not passed) and updating the test command output in kit.
> 
> I suggest we go ahead and update this now to reflect the changes

resolved on [2b7863a](https://github.com/OpenFn/docs/pull/319/commits/2b7863acee5f0ec35c9b0cfd1078831cd71c254e)

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@mtuchi , looks like 114 unintentional image changes. can you sort that out and re-open/re-request review?

**Comment by mtuchi** [comment]
> @mtuchi , looks like 114 unintentional image changes. can you sort that out and re-open/re-request review?

@taylordowns2000 the image changes were intentional it was feedback from @stuartc that the images needs to be optimized because most of them were too big

**Review by taylordowns2000 — COMMENTED** [review]
great changes. have started standardizing and rebased. will ping on slack now.

**Pull request closed without merging**
