### PR TITLE
GitHub sync important considerations

### PR DESCRIPTION
**Pull request by mtuchi**
### Description

I have update the GitHub sync guide to include important considerations especially with job file path support 

Ref #539

### CODE REVIEW

**Review by aleksa-krolls — APPROVED** [review]

**Comment by aleksa-krolls** [comment]
this looks good to me and helpful. @christad92 is this all still accurate? If yes, can we merge?

**Comment by christad92** [comment]
> this looks good to me and helpful. @christad92 is this all still accurate? If yes, can we merge?

Thanks. taking a look at now.

**Comment by aleksa-krolls** [comment]
hey @christad92 can we merge this now?

**Comment by christad92** [comment]
I have some pending fixes I want to make tomorrow. I'll let you know as when I'm done with those.

**Review by christad92 — APPROVED** [review]
Thanks @mtuchi

**Comment by christad92** [comment]
> hey @christad92 can we merge this now?

Yes! I am good with this now. 

Thanks

**Pull request merged**
